// Regenerates the inline SVG icon sprite in www/index.html from Lucide source SVGs.
//
// The app ships as a plain single file with no build step, and it also runs offline inside
// the Capacitor Android wrapper — so the icons are committed straight into index.html rather
// than pulled from a CDN at runtime. This script exists only to (re)generate that block:
//
//   npm i --no-save lucide-static && node scripts/build-icons.js
//
// Add a name to ICONS, re-run, commit the result. Names are Lucide file names without ".svg".
const fs = require('fs');
const path = require('path');

const ICONS = [
  // --- sidebar / header ---
  'moon', 'sun',                       // theme toggle
  'settings', 'database',
  'file-text', 'shapes', 'table',      // the three card kinds: note / canvas / sheet
  'file-input',                        // import .md
  'trash-2', 'command', 'waypoints',   // trash / quick switcher / connection map
  'rows-3', 'folder', 'arrow-left',    // list density / group by tag / back
  'menu',                              // mobile sidebar toggle
  // --- note toolbar ---
  'printer', 'download', 'copy', 'palette', 'star',
  // --- canvas toolbar ---
  'undo-2', 'redo-2', 'grid-3x3', 'maximize', 'minus', 'plus',
  'mouse-pointer-2', 'sticky-note', 'square', 'circle', 'diamond',
  'type', 'frame', 'id-card', 'image',

  // --- 2단계: 모달 / 서식 도구모음 / 비교 패널 / 시트 편집기 / 캔버스 컨텍스트 툴바 ---
  'x', 'chevron-down', 'chevron-right', 'pencil', 'eye', 'book-open',
  'link', 'filter', 'file-output',                 // 링크 / 시트 필터 / CSV 내보내기
  'indent-increase', 'indent-decrease',            // 들여쓰기 / 내어쓰기
  'list-checks', 'lightbulb', 'triangle-alert', 'ban',  // 할 일 / 콜아웃 4종(sticky-note 재사용)
  'arrow-right', 'arrow-up', 'arrow-down', 'arrow-up-down', 'arrow-up-right',
  'rotate-ccw',                                    // 휴지통 복원
  'lock', 'lock-open', 'tag', 'check',
  'calendar', 'hash', 'circle-dot', 'square-check', 'sigma',  // 데이터베이스 속성 타입
  'search', 'columns-2', 'chevrons-down-up',       // 검색 / 비교 패널 / 그룹 전체 접기

  // --- 캔버스 컨텍스트 툴바 ---
  'bold', 'a-large-small',                          // 굵게 / 글자 크기
  'bring-to-front', 'send-to-back',                 // z 순서 (기존엔 정렬과 ⤒⤓ 를 공유하고 있었다)
  'align-start-vertical', 'align-center-vertical', 'align-end-vertical',
  'align-start-horizontal', 'align-center-horizontal', 'align-end-horizontal', // 캔버스 개체 정렬
  'link-2-off',                                     // 연결 해제
];

const SRC = path.join(__dirname, '..', 'node_modules', 'lucide-static', 'icons');
const TARGET = path.join(__dirname, '..', 'www', 'index.html');
const START = '<!-- ICON-SPRITE:START -->';
const END = '<!-- ICON-SPRITE:END -->';

const seen = new Set();
const symbols = [];
for (const name of ICONS) {
  if (seen.has(name)) throw new Error('duplicate icon in ICONS: ' + name);
  seen.add(name);
  const file = path.join(SRC, name + '.svg');
  if (!fs.existsSync(file)) throw new Error('no such Lucide icon: ' + name);
  // Keep only the drawing commands; stroke/fill/size all come from the .ic CSS class
  // so a single rule restyles every icon at once.
  const body = fs.readFileSync(file, 'utf8')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s+/g, ' ')
    .trim();
  if (!body) throw new Error('empty icon body: ' + name);
  symbols.push('<symbol id="ic-' + name + '" viewBox="0 0 24 24">' + body + '</symbol>');
}

const block = [
  START,
  '<!-- Generated by scripts/build-icons.js from lucide-static (MIT). Do not edit by hand. -->',
  '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">',
  ...symbols,
  '</svg>',
  END,
].join('\n');

const html = fs.readFileSync(TARGET, 'utf8');
const from = html.indexOf(START);
const to = html.indexOf(END);
if (from === -1 || to === -1) throw new Error('sprite markers not found in ' + TARGET);
fs.writeFileSync(TARGET, html.slice(0, from) + block + html.slice(to + END.length));
console.log('wrote ' + symbols.length + ' icons (' + block.length + ' bytes) into www/index.html');
